# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('body', tinymce.models.HTMLField()),
                ('from_address', models.CharField(max_length=100, verbose_name='From Address')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id', 'subject'],
            },
        ),
    ]
