# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='from_address',
        ),
    ]
